// teachers.js

const teachers = {
  "Dr. Ananya Sharma": [
    {
      day: "Monday",
      time: "09:00-10:30",
      dept: "AIML",
      sem: 1,
      section: "C",
      subject: "Python Programming",
    },
    {
      day: "Monday",
      time: "14:00-15:30",
      dept: "DS",
      sem: 5,
      section: "B",
      subject: "Data Mining",
    },
    {
      day: "Tuesday",
      time: "10:30-12:00",
      dept: "CSE",
      sem: 3,
      section: "A",
      subject: "Object-Oriented Programming",
    },
    {
      day: "Tuesday",
      time: "15:30-17:00",
      dept: "Cyber",
      sem: 7,
      section: "C",
      subject: "AI in Cybersecurity",
    },
    {
      day: "Wednesday",
      time: "09:00-10:30",
      dept: "AIML",
      sem: 5,
      section: "A",
      subject: "Machine Learning",
    },
    {
      day: "Wednesday",
      time: "13:00-14:30",
      dept: "IT",
      sem: 1,
      section: "B",
      subject: "C Programming",
    },
    {
      day: "Thursday",
      time: "11:00-12:30",
      dept: "DS",
      sem: 3,
      section: "C",
      subject: "Database Systems",
    },
    {
      day: "Thursday",
      time: "14:00-15:30",
      dept: "ECE",
      sem: 7,
      section: "A",
      subject: "Neural Networks",
    },
    {
      day: "Friday",
      time: "09:00-10:30",
      dept: "AIML",
      sem: 7,
      section: "B",
      subject: "Deep Learning",
    },
    {
      day: "Friday",
      time: "11:00-12:30",
      dept: "CSE",
      sem: 5,
      section: "C",
      subject: "Operating Systems",
    },
  ],

  "Prof. Ravi Menon": [
    {
      day: "Monday",
      time: "11:00-12:30",
      dept: "CSE",
      sem: 1,
      section: "A",
      subject: "Programming in C",
    },
    {
      day: "Monday",
      time: "15:30-17:00",
      dept: "CSE",
      sem: 3,
      section: "B",
      subject: "Data Structures",
    },
    {
      day: "Tuesday",
      time: "09:00-10:30",
      dept: "CSE",
      sem: 5,
      section: "A",
      subject: "Algorithms",
    },
    {
      day: "Tuesday",
      time: "14:00-15:30",
      dept: "CSE",
      sem: 7,
      section: "C",
      subject: "Advanced Algorithms",
    },
    {
      day: "Wednesday",
      time: "10:30-12:00",
      dept: "IT",
      sem: 3,
      section: "A",
      subject: "Database Management Systems",
    },
    {
      day: "Wednesday",
      time: "13:00-14:30",
      dept: "AIML",
      sem: 1,
      section: "C",
      subject: "Mathematics for AI",
    },
    {
      day: "Thursday",
      time: "09:00-10:30",
      dept: "Cyber",
      sem: 5,
      section: "B",
      subject: "Computer Networks",
    },
    {
      day: "Thursday",
      time: "15:30-17:00",
      dept: "Cyber",
      sem: 7,
      section: "A",
      subject: "Cryptography",
    },
    {
      day: "Friday",
      time: "11:00-12:30",
      dept: "DS",
      sem: 1,
      section: "B",
      subject: "Introduction to Data Science",
    },
    {
      day: "Friday",
      time: "14:00-15:30",
      dept: "ECE",
      sem: 5,
      section: "C",
      subject: "Digital Signal Processing",
    },
  ],

  "Dr. Sneha Kapoor": [
    {
      day: "Monday",
      time: "10:30-12:00",
      dept: "Cyber",
      sem: 1,
      section: "B",
      subject: "Fundamentals of Cybersecurity",
    },
    {
      day: "Monday",
      time: "14:00-15:30",
      dept: "Cyber",
      sem: 5,
      section: "C",
      subject: "Network Security",
    },
    {
      day: "Tuesday",
      time: "09:00-10:30",
      dept: "Cyber",
      sem: 7,
      section: "B",
      subject: "Cryptography & Blockchain",
    },
    {
      day: "Tuesday",
      time: "13:00-14:30",
      dept: "IT",
      sem: 1,
      section: "A",
      subject: "Computer Fundamentals",
    },
    {
      day: "Wednesday",
      time: "09:00-10:30",
      dept: "Cyber",
      sem: 3,
      section: "A",
      subject: "Ethical Hacking",
    },
    {
      day: "Wednesday",
      time: "15:30-17:00",
      dept: "CSE",
      sem: 7,
      section: "C",
      subject: "Distributed Systems Security",
    },
    {
      day: "Thursday",
      time: "10:30-12:00",
      dept: "ECE",
      sem: 3,
      section: "B",
      subject: "Computer Architecture",
    },
    {
      day: "Thursday",
      time: "14:00-15:30",
      dept: "EE",
      sem: 1,
      section: "A",
      subject: "Basic Electrical Engineering",
    },
    {
      day: "Friday",
      time: "09:00-10:30",
      dept: "Cyber",
      sem: 5,
      section: "A",
      subject: "Web Application Security",
    },
    {
      day: "Friday",
      time: "13:00-14:30",
      dept: "AIML",
      sem: 3,
      section: "C",
      subject: "AI Ethics & Privacy",
    },
  ],

  "Prof. Arvind Nair": [
    {
      day: "Monday",
      time: "09:00-10:30",
      dept: "ECE",
      sem: 1,
      section: "C",
      subject: "Basic Electronics",
    },
    {
      day: "Monday",
      time: "11:00-12:30",
      dept: "ECE",
      sem: 3,
      section: "A",
      subject: "Signals & Systems",
    },
    {
      day: "Tuesday",
      time: "14:00-15:30",
      dept: "ECE",
      sem: 5,
      section: "B",
      subject: "Microprocessors",
    },
    {
      day: "Tuesday",
      time: "15:30-17:00",
      dept: "ECE",
      sem: 7,
      section: "C",
      subject: "Embedded Systems",
    },
    {
      day: "Wednesday",
      time: "09:00-10:30",
      dept: "EE",
      sem: 1,
      section: "B",
      subject: "Circuit Theory",
    },
    {
      day: "Wednesday",
      time: "13:00-14:30",
      dept: "EE",
      sem: 3,
      section: "C",
      subject: "Power Electronics",
    },
    {
      day: "Thursday",
      time: "09:00-10:30",
      dept: "EE",
      sem: 5,
      section: "A",
      subject: "Control Systems",
    },
    {
      day: "Thursday",
      time: "11:00-12:30",
      dept: "EE",
      sem: 7,
      section: "B",
      subject: "Electrical Machines",
    },
    {
      day: "Friday",
      time: "10:30-12:00",
      dept: "ECE",
      sem: 5,
      section: "C",
      subject: "VLSI Design",
    },
    {
      day: "Friday",
      time: "14:00-15:30",
      dept: "ECE",
      sem: 7,
      section: "A",
      subject: "IoT Systems",
    },
  ],

  "Dr. Meera Joshi": [
    {
      day: "Monday",
      time: "09:00-10:30",
      dept: "Business Systems",
      sem: 1,
      section: "A",
      subject: "Business Communication",
    },
    {
      day: "Monday",
      time: "13:00-14:30",
      dept: "Business Systems",
      sem: 3,
      section: "B",
      subject: "Accounting Basics",
    },
    {
      day: "Tuesday",
      time: "10:30-12:00",
      dept: "Business Systems",
      sem: 5,
      section: "C",
      subject: "Enterprise Systems",
    },
    {
      day: "Tuesday",
      time: "14:00-15:30",
      dept: "IT",
      sem: 7,
      section: "B",
      subject: "Cloud Computing",
    },
    {
      day: "Wednesday",
      time: "09:00-10:30",
      dept: "IT",
      sem: 1,
      section: "C",
      subject: "Introduction to IT",
    },
    {
      day: "Wednesday",
      time: "15:30-17:00",
      dept: "Business Systems",
      sem: 7,
      section: "A",
      subject: "Business Analytics",
    },
    {
      day: "Thursday",
      time: "09:00-10:30",
      dept: "IT",
      sem: 3,
      section: "B",
      subject: "Software Engineering",
    },
    {
      day: "Thursday",
      time: "14:00-15:30",
      dept: "IT",
      sem: 5,
      section: "A",
      subject: "Web Development",
    },
    {
      day: "Friday",
      time: "11:00-12:30",
      dept: "Business Systems",
      sem: 5,
      section: "B",
      subject: "Management Information Systems",
    },
    {
      day: "Friday",
      time: "14:00-15:30",
      dept: "IT",
      sem: 7,
      section: "C",
      subject: "Big Data Analytics",
    },
  ],
};

module.exports = teachers;
